<!DOCTYPE html>
<html>
<head>
    <title>中医药健康保健方案制定</title>
    <link media="all" type="text/css" rel="stylesheet" href="https://dn-qinco.qbox.me/humancss/0.13/css.min.css">
    <link media="all" type="text/css" rel="stylesheet" href="https://obycohhl2.qnssl.com/font-awesome-4.4/css/font-awesome.min.css">

    <style type="text/css">
        li {
            margin:10px 10px;
            padding:10px 10px;
        }
    </style>
</head>
<body class='bg-light'>



    <div class='alert alert-thick' id='root'>
        <div class='alert alert-thick bg-white'>
            <div class='box'>
                <div class='col-sm col-sm-2'>
                        <zhi-comp @select=selectZhi :active=activeZhi></zhi-comp>
                </div>
                <div class='col-sm col-sm-2'>
                    <div class='box none' id='col-2'>
                        <cate-comp @select=selectCate :active=activeCate></cate-comp>
                    </div>
                </div>
                <div class='col-sm col-sm-4'>
                    <div class='box none' id='col-3'>
                        <item-comp @select=selectItem :active=activeItem></item-comp>
                    </div>
                </div>
                <div class='col-sm col-sm-4'>
                    <div class='box none' id='col-4'>
                        <div v-if='result=="right"' class='alert alert-thin bd bd-3px bd-solid bd-green c-green'>
                            <h2>
                                <i class="fa fa-check"></i>
                            </h2>
                        </div>

                        <div v-else class='alert alert-thin bd bd-3px bd-solid bd-red c-red'>
                            <h2>
                                {{result}}
                            </h2>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>

<!--                 <span v-if="active(one.code)" class='btn btn-sm btn-red btn-square' style='position:absolute;bottom:0;right:0;'><i class='fa fa-check'></i></span> -->

    
    <script src="/vue.min.js"></script>
    <script src="https://obycohhl2.qnssl.com/jquery/jquery-1.11.0.min.js"></script>
    <script type="text/javascript">

        Vue.component('zhi-comp',{

            props:['active'],

            template: `
            <div>
                <ul v-for="one in this.$parent.zhis">
                    <li @click="$emit('select',one.code)""><a  :class="{'bg-violet c-white':active(one.code)}" class="btn-md btnl-violet">{{ one.name }}</a></li>
                </ul>
            </div>
            `,


        });


        Vue.component('cate-comp',{

            props:['active'],

            template: `
            <div>
                <ul v-for="one in this.$parent.cates">
                    <li @click="$emit('select',one.code)""><a  :class="{'bg-orange c-white':active(one.code)}" class="btn-md btnl-orange">{{ one.name }}</a></li>
                </ul>
            </div>
            `,


        });

        Vue.component('item-comp',{

            props:['active'],

            template: `
            <div>
                <ul v-for="one in this.$parent.items">
                    <li @click="$emit('select',one.code)""><a  :class="{'bg-blue c-white':active(one.code)}" class="btn-md btnl-blue">{{ one.name }}</a></li>
                </ul>
            </div>
            `,


        });

        var app = new Vue({
            el:'#root',

            data:{
                zhi:'',
                cate:'',
                item:'',
                result:'',
                zhis:[{code:1,name:'气虚质'},{code:2,name:'阳虚质'},{code:3,name:'阴虚质'},{code:4,name:'痰湿质'},{code:5,name:'湿热质'},{code:6,name:'气郁质'},{code:7,name:'血瘀质'},{code:8,name:'特禀质'}],
                cates:[{code:1,name:'情志调摄'},{code:2,name:'起居调护'},{code:3,name:'饮食调养'},{code:4,name:'运动保健'},{code:5,name:'经穴保健'}],
                items:[],
            },

            methods: {

                selectZhi: function(zhi) {

                    self = this;

                    self.zhi = zhi;

                    $('#col-2').show();


                },


                activeZhi: function(zhi) {
                    return (this.zhi === zhi); 
                },

                selectCate: function(cate) {

                    self = this;

                    self.cate = cate;

                    $.post(
                        '/displayitems',
                        {'cate':self.cate},
                        function(data)
                        {
                            self.items = data;
                        },
                        'json'
                    );

                    $('#col-3').show();


                },


                activeCate: function(cate) {
                    return (this.cate === cate); 
                },

                selectItem: function(item) {
                    self = this;
                    self.item = item;

                    $.post(
                        '/submit',
                        {'zhi':self.zhi,'cate':self.cate,'item':self.item},
                        function(data)
                        {
                            self.result = data;
                            console.log(data);
                        },
                        'json'
                    );

                    $('#col-4').show();

                },

                activeItem: function(item) {
                    return (this.item === item); 
                },


            }



        });
    </script>
</body>
</html>